return {
  {
    "nvim-treesitter/nvim-treesitter",
    opts_extend = { "ensure_installed" },
    opts = {
      ensure_installed = {
        -- Core languages
        "python",
        "javascript",
        "typescript",
        "tsx",
        "c",
        "cpp",
        "c_sharp",
        "java",
        "sql",
        "css",
        "scss",
        "html",
        "json",
        "yaml",
        "toml",
        "xml",
        "markdown",
        "markdown_inline",
        -- Additional languages
        "bash",
        "csv",
        "dockerfile",
        "elixir",
        "embedded_template",
        "go",
        "heex",
        "helm",
        "htmldjango",
        "ini",
        "kdl",
        "liquid",
        "lua",
        "nginx",
        "ron",
        "ruby",
        "rust",
        "terraform",
        "vim",
        "vimdoc",
        "regex",
        "query",
      },
    },
  },
}
